### ISSUE TITLE
Problème de reset quand le jeu est rejoué

### ISSUE THREAD

**Issue by moelumi** [Daydreel/hel_seej_2023#10]
Si le joueur rejoue au jeu après avoir fini la première fois sans relancer le jeu, les choix de tout les dialogues sont remplacé par le faux choix du dernier segment et l’événement du dernier segment est activé (moines qui cours + porte ouverte).

**Comment by Daydreel** [comment]
Il faut reset les variables globales lorsqu'on arrive sur la scène.
Dans le script du node main, appeler une fonction de l'objet en autoload DataPlayer qui reset ses variables

**Comment by Daydreel** [comment]
Fait
